services:
  dozzle:
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_MODE=swarm
      - DOZZLE_AUTH_PROVIDER=simple
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${STORAGE}/shared/dozzle:/data
    ports:
      - 8080
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role == manager" 