services:
  dozzle:
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_MODE=swarm
      - DOZZLE_AUTH_PROVIDER=simple
      - DOZZLE_LEVEL=debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_FOLDER}/creds/dozzle:/data
    #    ports:
    #      - 8080
    #    networks:
    #      - dozzle
    deploy:
      mode: global
#networks:
#  dozzle:
#    driver: overlay
