services:
  dozzle:
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_AUTH_PROVIDER=simple
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${STORAGE}/creds/dozzle:/data
    ports:
      - 8080:${OUTPUT_PORT}
    deploy:
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}