services:
  dozzle:
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_MODE=swarm
      - DOZZLE_AUTH_PROVIDER=simple
      # - DOZZLE_REMOTE_AGENT=rdm-p3:8083,rdm-p4:8084
      # - DOZZLE_LEVEL=debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${STORAGE}/dozzle:/data
    ports:
      - 8080
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role == manager"
  # dozzle-agent-rdm-p3:
  #   image: amir20/dozzle:latest
  #   command: agent
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   ports:
  #     - 8083:7007
  #   deploy:
  #     replicas: 1
  #     placement:
  #       constraints:
  #         - node.hostname == rdm-p3
  # dozzle-agent-rdm-p4:
  #   image: amir20/dozzle:latest
  #   command: agent
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   ports:
  #     - 8084:7007
  #   deploy:
  #     replicas: 1
  #     placement:
  #       constraints:
  #         - node.hostname == rdm-p4