services:
  msconvert:
    image: ptrxyz/chemotion:msconvert-2.0.1
    volumes:
      - ${STORAGE}/shared/spectra:/shared:rw
    ports:
      - 
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == rdm-p4
