services:
  registry:
    image: registry:latest
    volumes:
      - ${STORAGE}/registry:/var/lib/registry
    ports:
      - 5000
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOT=/var/lib/registry
      - REGISTRY_AUTH=htpasswd      
      - REGISTRY_AUTH_HTPASSWD_PATH=/var/lib/registry/creds/htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Chemotion
      - OTEL_TRACES_EXPORTER=none
