services:
  registry:
    image: registry:latest
    volumes:
      - ${STORAGE}/registry:/var/lib/registry
      - ${STORAGE}/creds/registry/htpasswd:/auth/htpasswd
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOT=/var/lib/registry
      - REGISTRY_AUTH=htpasswd      
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Chemotion
