services:
  registry:
    image: registry:latest
    hostname: registry
    volumes:
      - ${DATA_FOLDER}/data/registry:/var/lib/registry
      - ${DATA_FOLDER}/creds/registry/htpasswd:/auth/htpasswd
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOT=/var/lib/registry
      - REGISTRY_AUTH=htpasswd      
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Chemotion
      - REGISTRY_HTTP_HEADERS_Access-Control-All-Origins=["*"]
  registry-ui:
    image: joxit/docker-registry-ui:main
    environment:
      - REGISTRY_TITLE=Chemotion Image Registry
      - DEFAULT_REGISTRIES=http://registry:5000
      - READ_ONLY_REGISTRIES=true
      - SINGLE_REGISTRY=true